import i1 from "./Bell";
import i2 from "./Arrow";
import i3 from "./Close";
import i4 from "./MenuRight";
import i4b from "./MenuLeft";
import i5 from "./Clip";
import i6 from "./Oval";
import i7 from "./Play";
import i8 from "./Plus";
import i9 from "./Star";
import i10 from "./Check";

export const BellIcon = i1;
export const ArrowIcon = i2;
export const CloseIcon = i3;
export const MenuRightIcon = i4;
export const MenuLeftIcon = i4b;
export const ClipIcon = i5;
export const OvalIcon = i6;
export const PlayIcon = i7;
export const PlusIcon = i8;
export const StarIcon = i9;
export const CheckIcon = i10;
